### ISSUE TITLE
Calculation bug in requests per backend

### ISSUE THREAD

**Issue by towolf** [hnlq715/nginx-vts-exporter#61]
I think that PR #60 introduced a bug, the numbers do not add up:
![image](https://user-images.githubusercontent.com/345210/37918040-3bf8f770-3120-11e8-9fe4-00fff8d8d723.png)
They cumulate up to the total:

```
nginx_upstream_requests{backend="10.216.0.11:32154",code="total",redacted} 15110
nginx_upstream_requests{backend="10.216.0.12:32154",code="total",redacted} 30210
nginx_upstream_requests{backend="10.216.0.15:32154",code="total",redacted} 45306
nginx_upstream_requests{backend="10.216.0.16:32154",code="total",redacted} 60400
nginx_upstream_requests{backend="10.216.0.17:32154",code="total",redacted} 75493
nginx_upstream_requests{backend="10.216.0.18:32154",code="total",redacted} 90584
nginx_upstream_requests{backend="10.216.0.19:32154",code="total",redacted} 105674
nginx_upstream_requests{backend="10.216.0.21:32154",code="total",redacted} 120764
nginx_upstream_requests{backend="10.216.0.22:32154",code="total",redacted} 135862
```
```
nginx_server_requests{code="total",host="redacted"} 135987
```

**Comment by towolf** [comment]
@virtualroot Could you verify this?

**Comment by towolf** [comment]
Here's a visual:
![image](https://user-images.githubusercontent.com/345210/37920106-423bb414-3126-11e8-81b6-b8b6a6d39d7a.png)

**Comment by hadret** [comment]
I went through the code and to my limited understanding, these are quite simple counters. I'm not sure where the problem lies and whether it is actual problem, but please let me know @towolf do you agree with the following:

1. All of the requests (total, 1xx, 2xx etc.) are counters (i.e. they only grow over time).
2. Initial counter should equal number provided and observed in vts (i.e. not zero or random number).
3. Counter should be updated as per value provided by vts we changed over time.

In my observation, the last point is not "entirely" true. Counters are updated, but they differ from what I can see in vts. I cannot tell whether the problem is with my logic (as in: my expectations are not matching reality) or is it a broken software or maybe broken implementation.

@hnlq715 would you be so kind and find some spare moment to have a quick look onto the aforementioned PR #60 -- maybe it's some small omission/gotcha.

**Comment by towolf** [comment]
The values are cumulated and that is wrong. They should be added.

**Comment by hnlq715** [comment]
I got it, and will fix it ASAP, thanks for reporting!

**Comment by hnlq715** [comment]
@towolf 
please check [v0.10.1](https://github.com/hnlq715/nginx-vts-exporter/releases/tag/v0.10.1)

**Comment by hadret** [comment]
@towolf & @hnlq715 many thanks you guys!

**Comment by towolf** [comment]
@hnlq715 confimed fixed, the numbers agree now. Thanks!

**Comment by hnlq715** [comment]
nice
